apiVersion: v1
kind: Service
metadata:
  name: local-registry
  labels:
    app: docker-registry
    role: access
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30001
  selector:
    app: docker-registry
    role: backend