apiVersion: v1
kind: Service
metadata:
  name: kytos-openflow
  labels:
    app: kytos
    role: openflow
spec:
  type: NodePort
  ports:
  - port: 6653
    targetPort: 6653
    nodePort: 30003
  selector:
    app: kytos
    role: controller